# application name setting : Allow logging and management tools to identify the application
spring.application.name=minilog-jpa

# db url setting : allow application to access Mysql
spring.datasource.url=${DB_URL}?serverTimezone=Asia/Seoul
# DB access user setting
spring.datasource.username=${DB_USERNAME}
# DB password setting
spring.datasource.password=${DB_PASSWORD}
# jdbc driver setting: allow application to access Mysql by using JDBC driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate DDL setting: Automatically update DB schema (tables and columns) during development
# none: No action taken (Recommended for Production)
# create: Drops and recreates the schema on every startup (Recommended for Testing)
# create-drop: Creates schema on startup and drops it on shutdown (Recommended for Testing)
# update: Modifies the schema to match new changes while preserving existing data (Recommended for Development)
# validate: Checks if Entity maps to DB schema; throws an error if mismatched
spring.jpa.hibernate.ddl-auto=update
# SQL query logging setting: Print executed SQL queries to console
spring.jpa.show-sql=true

